# Generated by Django 2.1.5 on 2019-02-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=60)),
                ('author_email', models.CharField(max_length=100)),
                ('author_url', models.CharField(max_length=200)),
                ('author_ip', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('date_gmt', models.DateTimeField()),
                ('content', models.TextField()),
                ('karma', models.IntegerField()),
                ('agent', models.CharField(max_length=255)),
                ('comment_type', models.CharField(max_length=20)),
                ('approved', models.CharField(max_length=20)),
                ('parent', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CmsCommentMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.TextField()),
                ('cms_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsComment')),
            ],
        ),
        migrations.CreateModel(
            name='CmsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('visible', models.CharField(max_length=255)),
                ('owner', models.BigIntegerField()),
                ('rating', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('rel', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('rss', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CmsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('value', models.TextField()),
                ('autoload', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CmsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_gmt', models.DateTimeField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=280)),
                ('excerpt', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('to_ping', models.CharField(max_length=200)),
                ('pinged', models.CharField(max_length=200)),
                ('modified_date', models.DateTimeField()),
                ('modified_date_gmt', models.DateTimeField()),
                ('content_filtered', models.TextField()),
                ('parent', models.BigIntegerField()),
                ('guid', models.CharField(max_length=255)),
                ('menu_order', models.IntegerField()),
                ('post_type', models.CharField(max_length=20)),
                ('post_mime_type', models.CharField(max_length=100)),
                ('comment_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CmsPostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.TextField()),
                ('cms_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsPost')),
            ],
        ),
        migrations.CreateModel(
            name='CmsTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('parent', models.BigIntegerField()),
                ('count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CmsTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('term_group', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CmsTermMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.TextField()),
                ('cms_term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsTerm')),
            ],
        ),
        migrations.CreateModel(
            name='CmsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('nice_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('registred', models.DateTimeField()),
                ('activation_key', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('display_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CmsUserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.TextField()),
                ('cms_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsUser')),
            ],
        ),
        migrations.AddField(
            model_name='cmstaxonomy',
            name='cms_term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsTerm'),
        ),
        migrations.AddField(
            model_name='cmstaxonomy',
            name='posts',
            field=models.ManyToManyField(to='cms.CmsPost'),
        ),
        migrations.AddField(
            model_name='cmspost',
            name='cms_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsUser'),
        ),
        migrations.AddField(
            model_name='cmscomment',
            name='cms_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsUser'),
        ),
        migrations.AddField(
            model_name='cmscomment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CmsPost'),
        ),
    ]
